from pydantic import BaseModel,Field
from datetime import datetime
from .common import ORMModel
class ProductCreate(BaseModel): sku:str=Field(min_length=2,max_length=60); name:str=Field(min_length=2,max_length=150); category:str=Field(default='GOLD',max_length=80); description:str|None=None; unit_weight_g:float|None=Field(default=None,ge=0); price:float|None=Field(default=None,ge=0); quantity:float=Field(default=0,ge=0); min_quantity:float=Field(default=2,ge=0); unit:str=Field(default='pcs',max_length=12); purity:str|None=Field(default=None,max_length=24)
class ProductUpdate(BaseModel): name:str|None=Field(default=None,min_length=2,max_length=150); category:str|None=Field(default=None,max_length=80); description:str|None=None; unit_weight_g:float|None=Field(default=None,ge=0); price:float|None=Field(default=None,ge=0); quantity:float|None=Field(default=None,ge=0); min_quantity:float|None=Field(default=None,ge=0); unit:str|None=Field(default=None,max_length=12); purity:str|None=Field(default=None,max_length=24); is_active:bool|None=None
class ProductOut(ORMModel): id:int; sku:str; name:str; category:str; description:str|None; unit_weight_g:float|None; price:float|None; quantity:float; reserved_quantity:float; available_quantity:float; min_quantity:float; unit:str; purity:str|None; is_active:bool; created_at:datetime
class StockAdjust(BaseModel): delta:float; reason:str=Field(min_length=3,max_length=500); reference:str|None=None; transaction_date:datetime|None=None
class StockChange(BaseModel): quantity:float=Field(gt=0); reason:str=Field(min_length=3,max_length=500); reference:str|None=None; transaction_date:datetime|None=None
class StockReserve(BaseModel): quantity:float=Field(gt=0)
class InventoryTransactionOut(ORMModel): id:int; product_id:int; transaction_type:str; quantity_delta:float; reserved_delta:float; balance_after:float; unit:str; reference:str|None; reason:str|None; order_id:int|None; order_item_id:int|None; reversal_of_id:int|None; user_id:int|None; created_at:datetime
